@startuml
'https://plantuml.com/sequence-diagram

autonumber

Gitlab->Gitlab:开发feature1并合入master
Gitlab->Gitlab:开发feature2并合入master
Gitlab->Gerrit:把master推到gerrit
Gerrit->Gerrit:把gitlab的master合并到gerrit的master
Gerrit->Gitlab:把Gerrit的最新master拉到gitlab作为新的master
Gerrit->Rom:执行打包、测试等后续流程
Gitlab->Gitlab:开发feature3并合入master
Gitlab->Gitlab:开发feature4并合入master
Gitlab->Gerrit:把master推到gerrit
Gerrit->Gerrit:把gitlab的master合并到gerrit的master
Gerrit->Gitlab:把Gerrit的最新master拉到gitlab作为新的master
Gerrit->Rom:执行打包、测试等后续流程
@enduml