@startuml
'https://plantuml.com/sequence-diagram

autonumber

UnitySDK -> Loader: Get Product List
Loader -> MatrixCpp: Get Product List
MatrixCpp -> MatrixJava: Get Product List
MatrixJava->Server: Get Product List

@enduml